ignore file

diff --git a/.github/workflows/export-script.yml b/.github/workflows/export-script.yml
--- a/.github/workflows/export-script.yml
+++ b/.github/workflows/export-script.yml
@@ -40,7 +40,7 @@ jobs:
         while read -r file; do
           if [ -f "$file" ]; then
             mkdir -p "sql_upload/$(dirname "$file")"
-            cp --parents "$file" sql_upload/
+            cp --parents "$file" sql_upload/ || echo "cp failed: $file"
           else
             echo "File not found: $file"
           fi
